name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2

    - name: Update apt packages
      run: sudo apt-get update

    - uses: actions/setup-node@v2
      with:
        node-version: '18.x'
    - name: Install dependencies
      run: npm ci

    # - name: Create .env file
    #   run: |
    #     echo "MAILSAC_API_KEY=${{ secrets.MAILSAC_API_KEY }}" >> .env
    #     echo "OUTSETA_API_KEY=${{ secrets.OUTSETA_API_KEY }}" >> .env
    #     echo "OUTSETA_API_SECRET=${{ secrets.OUTSETA_API_SECRET }}" >> .env

    - name: Run API tests
      run: npm run test
      continue-on-error: true 

    - name: Generate Allure Report
      if: always()
      run: npm run allure-report

    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: api-test-results
        path: test-results/

    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: allure-test-results
        path: allure-report/

    - name: Get Allure history
      uses: actions/checkout@v2
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages

    - name: Allure Report action from marketplace
      uses: simple-elf/allure-report-action@master
      if: always()
      with:
        allure_results: allure-results
        allure_history: allure-history
        keep_reports: 20

    - name: Deploy report to Github Pages
      if: always()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: allure-history
